from supabase import create_client

SUPABASE_URL = "https://xvomgxdlnohtrgpdyrhs.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh2b21neGRsbm9odHJncGR5cmhzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjMzNTk0NDYsImV4cCI6MjA3ODkzNTQ0Nn0.cx1CR5WZ3wdBZ9XWoWpx5-0W9MelMyty4i4QEQ9tYIs"
supabase = create_client(SUPABASE_URL, SUPABASE_KEY)
